# Generated by Django 5.0.6 on 2024-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Untitled Income', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='Untitled Income', max_length=100),
        ),
    ]
